### ISSUE TITLE
Solution branch does not pass the tests

### ISSUE THREAD

**Issue by cnlucke** [learn-co-curriculum/redux-initial-dispatch#9]
I was having trouble getting the tests to execute successfully against my own code so on a whim I switched to the solution branch and ran the tests to see if the tests were just broken. While the tests finally executed successfully, the solution branch fails the tests with this logging:

  1) managePets reducer adds the pet when type is ADD_PET and the action has a payload property with the pet:

      Error: Expected { pets: [ { name: 'Splash', type: 'turtle', id: 100 }, undefined ] } to equal { pets: [ { name: 'Splash', type: 'turtle', id: 100 }, { name: 'avalanche', species: 'puppy', id: 101 } ] }
      + expected - actual

             "id": 100
             "name": "Splash"
             "type": "turtle"
           }
      -    [undefined]
      +    {
      +      "id": 101
      +      "name": "avalanche"
      +      "species": "puppy"
      +    }
         ]
       }
      
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:14:107)
      at callFn (node_modules/mocha-nocache/lib/runnable.js:286:21)
      at Test.Runnable.run (node_modules/mocha-nocache/lib/runnable.js:279:7)
      at Runner.runTest (node_modules/mocha-nocache/lib/runner.js:421:10)
      at node_modules/mocha-nocache/lib/runner.js:528:12
      at next (node_modules/mocha-nocache/lib/runner.js:341:14)
      at node_modules/mocha-nocache/lib/runner.js:351:7
      at next (node_modules/mocha-nocache/lib/runner.js:283:14)
      at Immediate.<anonymous> (node_modules/mocha-nocache/lib/runner.js:319:5)

  2) managePets reducer removes the pet when action type is REMOVE_PET and the action has a payload property of the id of pet to be removed:

      Error: Expected { pets: [ { name: 'avalanche', species: 'puppy', id: 101 }, { name: 'sally', species: 'camel', id: 102 } ] } to equal { pets: [ { name: 'Splash', species: 'Turtle' }, { name: 'sally', species: 'camel', id: 102 } ] }
      + expected - actual

       {
         "pets": [
           {
      -      "id": 101
      -      "name": "avalanche"
      -      "species": "puppy"
      +      "name": "Splash"
      +      "species": "Turtle"
           }
           {
             "id": 102
             "name": "sally"
      
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:19:67)
      at callFn (node_modules/mocha-nocache/lib/runnable.js:286:21)
      at Test.Runnable.run (node_modules/mocha-nocache/lib/runnable.js:279:7)
      at Runner.runTest (node_modules/mocha-nocache/lib/runner.js:421:10)
      at node_modules/mocha-nocache/lib/runner.js:528:12
      at next (node_modules/mocha-nocache/lib/runner.js:341:14)
      at node_modules/mocha-nocache/lib/runner.js:351:7
      at next (node_modules/mocha-nocache/lib/runner.js:283:14)
      at Immediate.<anonymous> (node_modules/mocha-nocache/lib/runner.js:319:5)

  3) render displays the state on the html:
     TypeError: Cannot read property 'name' of undefined
      at src/reducers/managePets.js:37:19
      at Array.map (native)
      at render (src/reducers/managePets.js:36:29)
      at dispatch (src/reducers/managePets.js:31:3)
      at Context.<anonymous> (test/index-test.js:48:5)
      at callFn (node_modules/mocha-nocache/lib/runnable.js:286:21)
      at Test.Runnable.run (node_modules/mocha-nocache/lib/runnable.js:279:7)
      at Runner.runTest (node_modules/mocha-nocache/lib/runner.js:421:10)
      at node_modules/mocha-nocache/lib/runner.js:528:12
      at next (node_modules/mocha-nocache/lib/runner.js:341:14)
      at node_modules/mocha-nocache/lib/runner.js:351:7
      at next (node_modules/mocha-nocache/lib/runner.js:283:14)
      at Immediate.<anonymous> (node_modules/mocha-nocache/lib/runner.js:319:5)

  4) dispatch with render calls the render function which displays the updated html:
     TypeError: Cannot read property 'name' of undefined
      at src/reducers/managePets.js:37:19
      at Array.map (native)
      at render (src/reducers/managePets.js:36:29)
      at Object.dispatch (src/reducers/managePets.js:31:3)
      at Context.<anonymous> (test/index-test.js:63:13)
      at callFn (node_modules/mocha-nocache/lib/runnable.js:286:21)
      at Test.Runnable.run (node_modules/mocha-nocache/lib/runnable.js:279:7)
      at Runner.runTest (node_modules/mocha-nocache/lib/runner.js:421:10)
      at node_modules/mocha-nocache/lib/runner.js:528:12
      at next (node_modules/mocha-nocache/lib/runner.js:341:14)
      at node_modules/mocha-nocache/lib/runner.js:351:7
      at next (node_modules/mocha-nocache/lib/runner.js:283:14)
      at Immediate.<anonymous> (node_modules/mocha-nocache/lib/runner.js:319:5)

Seems like the solution branch should be passing the tests! I'm not sure if it's a problem with the solution or the tests.

Thanks!

**Comment by cnlucke** [comment]
Oops! I wrote this under the wrong lab by accident. Moving to correct lab...
